pdksync - (GH-iac-334) Remove Support for Ubuntu 16.04
puppetlabs/puppetlabs-docker pull request #807
Opened 2022-03-23 12:35 UTC by david22swan

(GH-iac-334) Remove Support for Ubuntu 16.04
pdk version: `2.1.0`

2022-03-23 15:20 UTC, LukasAud approved these changes

2022-03-24 09:30 UTC, bastelfreak requested changes
https://github.com/puppetlabs/puppetlabs-docker/search?q=14.04 also here the module contains some 14.04/16.04 specific code and I really think that should be cleaned up in combination with the metadata.json remove of those operating systems. Otherwise it's really complicated in the future to determine if a change is a breaking change or not.

2022-03-24 10:07 UTC, david22swan commented
@bastelfreak This is just a quick automated pr to drop support, will be going through each module afterwards to remove compatibility.

2022-03-24 10:22 UTC, LukasAud approved these changes

2022-03-24 10:39 UTC, merged