(CDPE-6220) Fix variable references in run.pp
puppetlabs/puppetlabs-docker pull request #977
Opened 2024-04-18 20:54 UTC by eputnam

## Summary

Currently, CD4PE is using this module as part of the version 5 installation. When we use docker::run, as part of starting up the application containers, we're getting warnings like this in the customer-facing terminal output:

Unknown variable: 'docker::docker_group'. (file: /Users/eric.putnam/ws/cd4pe/PipelinesInfra/deploy/envs/cdpe6633/.modules/docker/manifests/run.pp, line: 268, column: 19)
Unknown variable: 'docker::service_name'. (file: /Users/eric.putnam/ws/cd4pe/PipelinesInfra/deploy/envs/cdpe6633/.modules/docker/manifests/run.pp, line: 267, column: 19)

This doesn't make for a very good customer experience. Since these vars are in docker::params, I added "::params" to the two lines where docker_group and service_name are assigned and that seemed to take care of the warnings. Please correct me if I'm wrong about this change, our main goal is to get rid of these warnings.

## Additional Context
Add any additional context about the problem here. 
- [ ] Root cause and the steps to reproduce. (If applicable)
These warnings can be seen by running the following bolt plan, which requires this module:
```
plan whalesay::docker_run() {
  apply_prep('localhost')

  apply('localhost') {
    docker::run{'example run':
      image            => 'docker/whalesay',
      pull_on_start    => true,
      restart          => "no",
    }
  }
}
```

## Related Issues (if any)
Mention any related issues or pull requests.

## Checklist
- [ ] 🟢 Spec tests.
- [ ] 🟢 Acceptance tests.
- [ ] Manually verified. (For example `puppet apply`)

2024-04-18 21:11 UTC, smortex requested changes
Directly using `$docker::params::*` is not correct because it contain a default value for a parameter the end user may have provided a specific one.

I added details and a better approach in in-line comments.

Thanks!

2024-04-18 21:11 UTC, smortex commented on manifests/run.pp
> +  $docker_group = $docker::params::docker_group
[The `docker` class inherits form `docker::params`](https://github.com/puppetlabs/puppetlabs-docker/blob/8f4b3d98c7110e3a4fc9151a14e55876eec2b585/manifests/init.pp#L476) and [allow personalization of these parameters](https://github.com/puppetlabs/puppetlabs-docker/blob/8f4b3d98c7110e3a4fc9151a14e55876eec2b585/manifests/init.pp#L439-L442) (using the values from `docker::params` for default values if not provided).

In order to access `$docker::*` variables, including this class should be enough:

```puppet
  include docker
```

2024-04-19 00:00 UTC, kenyon commented
Also, `params.pp` should be eliminated, like what I've done for the APT module in https://github.com/puppetlabs/puppetlabs-apt/pull/1172. This docker module would take a lot more effort though.

2026-09-04 16:29 UTC, jst-cyr commented
@eputnam : Do you think this change in the docker module would still be valuable? This PR was unfortunately not looked into for quite some time and I'm wondering if it's still needed?

2026-09-18 14:57 UTC, jst-cyr commented
Closing this PR for now until a need rises for this in the future at which point we can re-open!

2026-09-18 14:57 UTC, closed without merging